version: '3.8'
services:
  discovery:
    image: tugayesilyurt/spring-eureka-server
    container_name: discovery-server
    build: 
       context: ./spring-eureka-server
       dockerfile: Dockerfile
    restart: on-failure
    network_mode: bridge
    ports:
      - "8761:8761"
    networks:
      - resilience-net
  gateway-service:
    image: tugayesilyurt/spring-cloud-gateway
    container_name: gateway-service
    network_mode: bridge
    build: 
       context: ./spring-cloud-gateway
       dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8090:8090"
    links:
      - discovery
    networks:
      - resilience-net
  customer-service:
    image: tugayesilyurt/customer-service
    container_name: customer-service
    network_mode: bridge
    build: 
       context: ./customer-service
       dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"
    links:
      - discovery 
    networks:
      - resilience-net  
  card-service:
    image: tugayesilyurt/card-service
    container_name: card-service
    network_mode: bridge
    build: 
       context: ./card-service
       dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "7000:7000"
    links:
      - discovery
    networks:
      - resilience-net      
  prometheus:
    container_name: prometheus
    network_mode: bridge
    ports:
        - "9090:9090"
    volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: '--config.file=/etc/prometheus/prometheus.yml'
    image: prom/prometheus
    networks:
      - resilience-net
  grafana:
    container_name: grafana
    network_mode: bridge
    ports:
        - "3000:3000"
    volumes:
        - /var/lib/grafana
    links:
    - prometheus
    image: grafana/grafana
    networks:
      - resilience-net
networks:
  resilience-net:
    external: true